{% set name = "fmrib-unpack-fmrib-config" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4e8a53a89ff6341158cc626cf53d0e0d91888ce4555bcbeb0ddb746b741a7b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

about:
  home: https://git.fmrib.ox.ac.uk/fsl/funpack-fmrib-config/
  summary: FMRIB configuration for FUNPACK
  description: |
    FUNPACK is a Python library for pre-processing of UK BioBank data. The
    fmrib-unpack-fmrib-config package contains a configuration profile for
    FUNPACK which encodes a large set of cleaning and processing rules for a
    range of UK BioBank data fields.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://open.win.ox.ac.uk/pages/fsl/funpack/
  dev_url: https://git.fmrib.ox.ac.uk/fsl/funpack-fmrib-config/

extra:
  recipe-maintainers:
    - pauldmccarthy
